Hw6
ruslan-ozorkin/a-level_3 pull request #4
Opened 2022-11-08 19:17 UTC by ruslan-ozorkin

hw6 done

2022-11-10 20:28 UTC, Fabolo12 requested changes

2022-11-10 20:28 UTC, Fabolo12 commented on src/main/java/com/ozorkin/Main.java
> +                new CarService().create(),
не нужно создавать сервис каждый раз, он у тебя есть на 10 строке

2022-11-10 20:28 UTC, Fabolo12 commented on src/main/java/com/ozorkin/service/CarService.java
> +        car.setCount(1);
Формирование строки надо вынести в отдельный метод

2022-11-10 20:28 UTC, Fabolo12 commented on src/main/java/com/ozorkin/model/Car.java
> +    Random random = new Random();
private

2022-11-11 16:02 UTC, ruslan-ozorkin commented
Спасибо, ошибки исправлены!

2022-11-11 23:06 UTC, Fabolo12 approved these changes

2022-11-12 17:53 UTC, merged